FROM mysql:oraclelinux9

RUN microdnf update -y \
    && microdnf install -y shadow-utils \
    && groupadd --system nonroot \
    && useradd --system --gid nonroot nonroot

USER nonroot

EXPOSE 3306

VOLUME /var/lib/mysql

CMD ["mysqld"]