FROM nginx:latest

COPY NGINX/default.conf /etc/nginx/conf.d/default.conf
COPY NGINX/passmanager.conf /etc/nginx/conf.d/passmanager.conf
COPY NGINX/index.html /usr/share/nginx/html/index.html
EXPOSE 80
EXPOSE 8080