FROM nginx:latest

COPY NGINX/default.conf /etc/nginx/conf.d/default.conf
COPY NGINX/formulariocitas.conf /etc/nginx/conf.d/formulariocitas.conf
COPY NGINX/index.html /usr/share/nginx/html/index.html
EXPOSE 80
EXPOSE 8080