FROM python:3.12-slim

WORKDIR /var/www/passmanager

COPY requirements.txt /var/www/passmanager/
RUN pip install --no-cache-dir -r  /var/www/passmanager/requirements.txt

COPY ./passmanager/ /var/www/passmanager/

RUN chown -R www-data:www-data /var/www/passmanager

EXPOSE 5000
USER www-data
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "wsgi:app"]