FROM nginx:stable-perl

RUN addgroup --system nonroot \
    && adduser --system --ingroup nonroot nonroot
# Switch to nonroot user


COPY --chown=root:root --chmod=755 NGINX/default.conf /etc/nginx/conf.d/default.conf
COPY --chown=root:root --chmod=755 NGINX/passmanager.conf /etc/nginx/conf.d/passmanager.conf
COPY --chown=root:root --chmod=755 NGINX/index.html /usr/share/nginx/html/index.html

# Switch to nonroot user
USER nonroot


EXPOSE 80
EXPOSE 8080